# Generated by Django 3.2.13 on 2022-05-31 14:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('product_title', models.CharField(max_length=1000)),
                ('product_url', models.CharField(max_length=1000)),
                ('product_image', models.CharField(max_length=1000)),
                ('product_binding', models.CharField(max_length=255, null=True)),
                ('product_group', models.CharField(max_length=255, null=True)),
                ('product_features', jsonfield.fields.JSONField()),
                ('product_height', models.CharField(max_length=255, null=True)),
                ('product_width', models.CharField(max_length=255, null=True)),
                ('product_weight', models.CharField(max_length=255, null=True)),
                ('product_length', models.CharField(max_length=255, null=True)),
                ('product_size', models.CharField(max_length=255, null=True)),
                ('product_manufacture_id', models.CharField(max_length=255, null=True)),
                ('product_manufacture_model', models.CharField(max_length=255, null=True)),
                ('product_manufacture_warranty', models.CharField(max_length=255, null=True)),
                ('product_merchant_name', models.CharField(max_length=255, null=True)),
                ('product_price', models.CharField(max_length=255)),
                ('product_discount', models.CharField(max_length=255, null=True)),
                ('product_discount_percentage', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
